= File Authentication Plugin Utility

== Build jar file

* +mvn package+
* Done! Jar file can be found in target folder.

== Usage

. Make sure the fileAuthConfiguration.properties have your desired settings
.
. Remove the provided credentials.properties
. Start utility on a Linux or OS/X based system with: +java -jar file-authentication-plugin-utility-1.1.jar+
. Configure the utility with: +configure --file path/to/fileAuthConfiguration.properties+
. Create as many user as you need with: +addUser --username <USERNAME> --password <PASSWORD>+
. Show all user: +listUsers+
. Done!

CAUTION: The utility does not support Windows. `credentials.properties` file must be created on Linux or OS/X

= Contributing

If you want to contribute to HiveMQ File Authentication Plugin Utility, see the link:CONTRIBUTING.md[contribution guidelines].

= License

HiveMQ File Authentication Plugin Utility is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE.txt[here].
